var Pre3d=function(){function x(a,b){return a.x*b.x+a.y*b.y+a.z*b.z}function J(a,b){return{x:a.x-b.x,y:a.y-b.y}}function A(a,b){return{x:a.x+b.x,y:a.y+b.y,z:a.z+b.z}}function K(a,b){return{x:a.x*b,y:a.y*b}}function L(a,b){return{x:a.x*b,y:a.y*b,z:a.z*b}}function M(a){var b=a.x;a=a.y;return Math.sqrt(b*b+a*a)}function N(a){var b=a.x,c=a.y;a=a.z;return Math.sqrt(b*b+c*c+a*a)}function O(a){return K(a,1/M(a))}function y(a){return L(a,1/N(a))}function q(a,b,c,e,g,d,h,f,j,l,k,m){this.e0=a;this.e1=b;this.e2=
c;this.e3=e;this.e4=g;this.e5=d;this.e6=h;this.e7=f;this.e8=j;this.e9=l;this.e10=k;this.e11=m}function p(a,b){var c=a.e0,e=a.e1,g=a.e2,d=a.e4,h=a.e5,f=a.e6,j=a.e8,l=a.e9,k=a.e10,m=b.e0,n=b.e1,i=b.e2,s=b.e3,B=b.e4,C=b.e5,D=b.e6,E=b.e7,F=b.e8,G=b.e9,H=b.e10,I=b.e11;return new q(c*m+e*B+g*F,c*n+e*C+g*G,c*i+e*D+g*H,c*s+e*E+g*I+a.e3,d*m+h*B+f*F,d*n+h*C+f*G,d*i+h*D+f*H,d*s+h*E+f*I+a.e7,j*m+l*B+k*F,j*n+l*C+k*G,j*i+l*D+k*H,j*s+l*E+k*I+a.e11)}function P(a){var b=Math.sin(a);a=Math.cos(a);return new q(1,0,
0,0,0,a,-b,0,0,b,a,0)}function Q(a){var b=Math.sin(a);a=Math.cos(a);return new q(a,0,b,0,0,1,0,0,-b,0,a,0)}function R(a){var b=Math.sin(a);a=Math.cos(a);return new q(a,-b,0,0,b,a,0,0,0,0,1,0)}function u(a,b){return{x:a.e0*b.x+a.e1*b.y+a.e2*b.z+a.e3,y:a.e4*b.x+a.e5*b.y+a.e6*b.z+a.e7,z:a.e8*b.x+a.e9*b.y+a.e10*b.z+a.e11}}function o(){this.reset()}function S(a,b){for(var c=b.length,e=Array(c),g=0;g<c;++g)e[g]=u(a,b[g]);return e}function w(a,b){var c=O(J(b,a));b.x+=c.x;b.y+=c.y;a.x-=c.x;a.y-=c.y}function t(a,
b,c,e){this.setRGBA(a,b,c,e)}function v(a,b,c,e){this.i0=a;this.i1=b;this.i2=c;this.i3=e;this.normal2=this.normal1=this.centroid=null}function z(a,b,c){this.ep=a;this.c0=b;this.c1=c}function T(){this.transform=new o;this.focal_length=1}function r(a){this.draw_overdraw=this.perform_z_sorting=true;this.draw_backfaces=false;this.texture=null;this.fill_rgba=new t(1,0,0,1);this.normal2_rgba=this.normal1_rgba=this.stroke_rgba=null;this.canvas=a;this.ctx=a.getContext("2d");this.camera=new T;this.transform=
new o;this.transform_stack_=[];this.quad_callback=null;this.width_=a.width;this.height_=a.height;this.scale_=this.height_/2;this.xoff_=this.width_/2;this.buffered_quads_=null;this.emptyBuffer();if(this.ctx.setStrokeColor==null)this.ctx.setStrokeColor=function(b,c,e,g){this.strokeStyle="rgba("+[Math.floor(b*255),Math.floor(c*255),Math.floor(e*255),g].join(",")+")"};if(this.ctx.setFillColor==null)this.ctx.setFillColor=function(b,c,e,g){this.fillStyle="rgba("+[Math.floor(b*255),Math.floor(c*255),Math.floor(e*
255),g].join(",")+")"}}function U(a,b,c,e,g,d,h,f,j,l,k,m,n,i){a.save();a.beginPath();a.moveTo(c,e);a.lineTo(g,d);a.lineTo(h,f);a.closePath();a.clip();var s=j*(i-m)-k*i+n*m+(k-n)*l;a.transform(-(l*(h-g)-m*h+i*g+(m-i)*c)/s,(m*f+l*(d-f)-i*d+(i-m)*e)/s,(j*(h-g)-k*h+n*g+(k-n)*c)/s,-(k*f+j*(d-f)-n*d+(n-k)*e)/s,(j*(i*g-m*h)+l*(k*h-n*g)+(n*m-k*i)*c)/s,(j*(i*d-m*f)+l*(k*f-n*d)+(n*m-k*i)*e)/s);a.drawImage(b,0,0);a.restore()}function V(a,b){return a.qf.centroid.z-b.qf.centroid.z}o.prototype.reset=function(){this.m=
new q(1,0,0,0,0,1,0,0,0,0,1,0)};o.prototype.rotateX=function(a){this.m=p(P(a),this.m)};o.prototype.rotateXPre=function(a){this.m=p(this.m,P(a))};o.prototype.rotateY=function(a){this.m=p(Q(a),this.m)};o.prototype.rotateYPre=function(a){this.m=p(this.m,Q(a))};o.prototype.rotateZ=function(a){this.m=p(R(a),this.m)};o.prototype.rotateZPre=function(a){this.m=p(this.m,R(a))};o.prototype.translate=function(a,b,c){this.m=p(new q(1,0,0,a,0,1,0,b,0,0,1,c),this.m)};o.prototype.translatePre=function(a,b,c){this.m=
p(this.m,new q(1,0,0,a,0,1,0,b,0,0,1,c))};o.prototype.scale=function(a,b,c){this.m=p(new q(a,0,0,0,0,b,0,0,0,0,c,0),this.m)};o.prototype.scalePre=function(a,b,c){this.m=p(this.m,new q(a,0,0,0,0,b,0,0,0,0,c,0))};o.prototype.transformPoint=function(a){return u(this.m,a)};o.prototype.multTransform=function(a){this.m=p(this.m,a.m)};o.prototype.setDCM=function(a,b,c){var e=this.m;e.e0=a.x;e.e4=a.y;e.e8=a.z;e.e1=b.x;e.e5=b.y;e.e9=b.z;e.e2=c.x;e.e6=c.y;e.e10=c.z};o.prototype.dup=function(){var a=new o;a.m=
new q(this.m.e0,this.m.e1,this.m.e2,this.m.e3,this.m.e4,this.m.e5,this.m.e6,this.m.e7,this.m.e8,this.m.e9,this.m.e10,this.m.e11);return a};t.prototype.setRGBA=function(a,b,c,e){this.r=a;this.g=b;this.b=c;this.a=e};t.prototype.setRGB=function(a,b,c){this.setRGBA(a,b,c,1)};t.prototype.invert=function(){this.r=1-this.r;this.g=1-this.g;this.b=1-this.b};t.prototype.dup=function(){return new t(this.r,this.g,this.b,this.a)};v.prototype.isTriangle=function(){return this.i3===null};v.prototype.setQuad=function(a,
b,c,e){this.i0=a;this.i1=b;this.i2=c;this.i3=e};v.prototype.setTriangle=function(a,b,c){this.i0=a;this.i1=b;this.i2=c;this.i3=null};z.prototype.isQuadratic=function(){return this.c1===null};z.prototype.setQuadratic=function(a,b){this.ep=a;this.c0=b;this.c1=null};z.prototype.setCubic=function(a,b,c){this.ep=a;this.c0=b;this.c1=c};r.prototype.pushTransform=function(){this.transform_stack_.push(this.transform.dup())};r.prototype.popTransform=function(){this.transform=this.transform_stack_.pop()};r.prototype.emptyBuffer=
function(){this.buffered_quads_=[]};r.prototype.projectPointToCanvas=function(a){var b=this.camera.focal_length/-a.z,c=this.scale_;return{x:a.x*b*c+this.xoff_,y:a.y*b*-c+c}};r.prototype.projectPointsToCanvas=function(a){for(var b=a.length,c=Array(b),e=0;e<b;++e)c[e]=this.projectPointToCanvas(a[e]);return c};r.prototype.projectQuadFaceToCanvasIP=function(a){a.i0=this.projectPointToCanvas(a.i0);a.i1=this.projectPointToCanvas(a.i1);a.i2=this.projectPointToCanvas(a.i2);if(!a.isTriangle())a.i3=this.projectPointToCanvas(a.i3);
return a};var W={x:0,y:0,z:1};r.prototype.bufferShape=function(a){var b=this.draw_backfaces,c=this.quad_callback,e=p(this.camera.transform.m,this.transform.m),g;g=e.e0;var d=e.e1,h=e.e2,f=e.e4,j=e.e5,l=e.e6,k=e.e8,m=e.e9,n=e.e10;g=new q(n*j-l*m,l*k-f*n,f*m-k*j,0,h*m-n*d,n*g-h*k,k*d-g*m,0,l*d-h*j,f*h-l*g,g*j-f*d,0);d=S(e,a.vertices);h=a.quads;f=0;for(j=a.quads.length;f<j;++f){var i=h[f];if(!(c!==null&&c(i,f,a)===true)){l=u(e,i.centroid);if(!(l.z>=-1)){k=y(u(g,i.normal1));m=u(g,i.normal2);if(!(b!==
true&&x(l,k)>0&&x(l,m)>0)){n=x(W,k);if(n<0)n=0;i=i.isTriangle()===true?new v(d[i.i0],d[i.i1],d[i.i2],null):new v(d[i.i0],d[i.i1],d[i.i2],d[i.i3]);i.centroid=l;i.normal1=k;i.normal2=m;this.buffered_quads_.push({qf:i,intensity:n,draw_overdraw:this.draw_overdraw,texture:this.texture,fill_rgba:this.fill_rgba,stroke_rgba:this.stroke_rgba,normal1_rgba:this.normal1_rgba,normal2_rgba:this.normal2_rgba})}}}}};r.prototype.drawBackground=function(){this.ctx.fillRect(0,0,this.width_,this.height_)};r.prototype.clearBackground=
function(){this.ctx.clearRect(0,0,this.width_,this.height_)};r.prototype.drawBuffer=function(){var a=this.ctx,b=this.buffered_quads_,c=b.length;this.perform_z_sorting===true&&b.sort(V);for(var e=0;e<c;++e){var g=b[e],d=g.qf;this.projectQuadFaceToCanvasIP(d);var h=d.isTriangle();if(g.draw_overdraw===true){w(d.i0,d.i1);w(d.i1,d.i2);if(h===true)w(d.i2,d.i0);else{w(d.i2,d.i3);w(d.i3,d.i0)}}a.beginPath();a.moveTo(d.i0.x,d.i0.y);a.lineTo(d.i1.x,d.i1.y);a.lineTo(d.i2.x,d.i2.y);h!==true&&a.lineTo(d.i3.x,
d.i3.y);var f=g.fill_rgba;if(f!==null){var j=g.intensity;a.setFillColor(f.r*j,f.g*j,f.b*j,f.a);a.fill()}f=g.texture;if(f!==null){U(a,f.image,d.i0.x,d.i0.y,d.i1.x,d.i1.y,d.i2.x,d.i2.y,f.u0,f.v0,f.u1,f.v1,f.u2,f.v2);h||U(a,f.image,d.i0.x,d.i0.y,d.i2.x,d.i2.y,d.i3.x,d.i3.y,f.u0,f.v0,f.u2,f.v2,f.u3,f.v3)}h=g.stroke_rgba;if(h!==null){a.closePath();a.setStrokeColor(h.r,h.g,h.b,h.a);a.stroke()}h=g.normal1_rgba;g=g.normal2_rgba;if(h!==null){a.setStrokeColor(h.r,h.g,h.b,h.a);h=this.projectPointToCanvas(d.centroid);
f=this.projectPointToCanvas(A(d.centroid,y(d.normal1)));a.beginPath();a.moveTo(h.x,h.y);a.lineTo(f.x,f.y);a.stroke()}if(g!==null){a.setStrokeColor(g.r,g.g,g.b,g.a);h=this.projectPointToCanvas(d.centroid);f=this.projectPointToCanvas(A(d.centroid,y(d.normal2)));a.beginPath();a.moveTo(h.x,h.y);a.lineTo(f.x,f.y);a.stroke()}}return c};r.prototype.drawPath=function(a,b){var c=this.ctx;b=b||{};var e=p(this.camera.transform.m,this.transform.m),g=this.projectPointsToCanvas(S(e,a.points));e=a.starting_point===
null?this.projectPointToCanvas(u(e,{x:0,y:0,z:0})):g[a.starting_point];c.beginPath();c.moveTo(e.x,e.y);e=a.curves;for(var d=0,h=e.length;d<h;++d){var f=e[d];if(f.isQuadratic()===true){var j=g[f.c0];f=g[f.ep];c.quadraticCurveTo(j.x,j.y,f.x,f.y)}else{j=g[f.c0];var l=g[f.c1];f=g[f.ep];c.bezierCurveTo(j.x,j.y,l.x,l.y,f.x,f.y)}}b.fill===true?c.fill():c.stroke()};return{RGBA:t,AffineMatrix:q,Transform:o,QuadFace:v,Shape:function(){this.vertices=[];this.quads=[]},Curve:z,Path:function(){this.points=[];this.curves=
[];this.starting_point=null},Camera:T,TextureInfo:function(){this.v3=this.u3=this.v2=this.u2=this.v1=this.u1=this.v0=this.u0=this.image=null},Renderer:r,Math:{crossProduct:function(a,b){return{x:a.y*b.z-a.z*b.y,y:a.z*b.x-a.x*b.z,z:a.x*b.y-a.y*b.x}},dotProduct2d:function(a,b){return a.x*b.x+a.y*b.y},dotProduct3d:x,subPoints2d:J,subPoints3d:function(a,b){return{x:a.x-b.x,y:a.y-b.y,z:a.z-b.z}},addPoints2d:function(a,b){return{x:a.x+b.x,y:a.y+b.y}},addPoints3d:A,mulPoint2d:K,mulPoint3d:L,vecMag2d:M,vecMag3d:N,
unitVector2d:O,unitVector3d:y,linearInterpolate:function(a,b,c){return(b-a)*c+a},linearInterpolatePoints3d:function(a,b,c){return{x:(b.x-a.x)*c+a.x,y:(b.y-a.y)*c+a.y,z:(b.z-a.z)*c+a.z}},averagePoints:function(a){for(var b={x:0,y:0,z:0},c=0,e=a.length;c<e;++c){var g=a[c];b.x+=g.x;b.y+=g.y;b.z+=g.z}a=1/e;b.x*=a;b.y*=a;b.z*=a;return b}}}}();
